hpa:
  enabled: true
  minReplicas: 6
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100

service:
  port: 80
  targetPort: 8080