---
# Source: nginx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
spec:
  type: 
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: test-nginx
---
# Source: nginx/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-nginx
  namespace: sandbox-nginx
spec:
  minReplicas: 6
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-nginx
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
